the tags from inside out.

<p><strong>Just some example content.</strong></p>
//Run the following command inside the folder
$ git init
//Run the following command to create a new directory that is a git repo
$ git init DIRECTORY_PATH/DIRECTORY_NAME

Hi

the tags from inside out.


⁵⅚
